Redux hooks
shiranka/TodoList pull request #2
Opened 2020-04-01 17:43 UTC by shiranka

2020-04-01 18:00 UTC, yotamberk requested changes

2020-04-01 18:00 UTC, yotamberk commented on my-app/src/components/TaskForm.js
> +                <input type="text" onChange={handleChange} placeholder='Add a task...' value={task}></input>
``` javascript
<input
   type="text" 
   placeholder='Add a task...' 
   onChange={handleChange} 
   value={task} 
/>
```

2020-04-01 18:00 UTC, yotamberk commented on my-app/src/components/TaskForm.js
> +    return (
add a new line

2020-04-01 18:00 UTC, yotamberk commented on my-app/src/components/TaskForm.js
> +    const handleChange = (e) => { setTask(e.target.value) }
use `useCallback()` to remove the redefinition of this function.

2020-04-01 18:00 UTC, yotamberk commented on my-app/src/components/TaskForm.js
> +    const handleSubmit = (e) => {
same here. use `useCallback`

2020-04-01 18:00 UTC, yotamberk commented on my-app/src/components/TasksList.js
> +    const deleteTask = (id) => dispatch(deleteTaskAction(id))
convert to be a closure: `(id) => () => dispatch(deleteTaskAction(id))` and wrap with `useCallback` so it gets memoized

2020-04-01 18:00 UTC, yotamberk commented on my-app/src/components/TasksList.js
> +                <button onClick={() => deleteTask(task.id)}>x</button>
and then you can use `onClick={deleteTask(task.id)}` without redefining this function

2020-04-01 18:00 UTC, yotamberk commented on my-app/src/redux.js
> +        case 'add_task':
reducer types must be all capital like `ADD_TASK`

2020-04-05 19:21 UTC, yotamberk approved these changes
Nice and clean! Very good!

2020-04-06 10:50 UTC, avishag410 commented on my-app/src/components/TasksList.js
> +                <div className="collection-item" key={task.id}>
there is no existing class "collection-item"

2020-04-06 10:51 UTC, avishag410 commented on my-app/src/redux.js
> +import { createStore } from 'redux'
please separate the file to actions and reducres

2020-04-06 10:58 UTC, avishag410 commented on my-app/src/components/TaskForm.js
> +                    onChange={handleChange}
when calling on change from component, I'd rather u will use the following scheme:

<MyComponent
...
onChange={(e) => handleChange(e.target.value)}
/>

.....
const ... handleChange(Input) {
 setSomething(input)
}

2020-04-06 12:45 UTC, avishag410 commented on my-app/src/components/TaskForm.js
> +    const handleChange = useCallback((input) => {
your changes are what i meant, but use a different variable name, `input` is not meaningful

2020-04-06 12:47 UTC, avishag410 commented on my-app/src/redux/store.js
> +import { createStore } from 'redux'
you don't need a different file for the store, it should be in the file with the reducer

2020-04-08 09:09 UTC, merged